### ISSUE TITLE
Backlog for Connect-ES documentation

### ISSUE THREAD

**Issue by timostamm** [connectrpc/connectrpc.com#41]
- [x] Clients: Document the `timeoutMs` option: How to catch; Interop with gRPC; Code deadline_exceeded.
- [ ] Clients: Document common use cases for interceptors.
- [x] Web clients: Document how to set fetch properties in the [interceptors](https://connectrpc.com/docs/web/interceptors) section.
- [x] Web clients: Document how to bring your own `fetch`.
- [ ] Web clients: Document how to debug RPCs in the browser's network explorer.
- [x] Clients: Link to the [custom client example](https://github.com/connectrpc/examples-es/tree/main/custom-client) from the [roll your own client](https://connectrpc.com/docs/web/using-clients#roll-your-own-client) section.
- [x] Clients: Document context values (see [v1.1.0 release notes](https://github.com/connectrpc/connect-es/releases/tag/v1.1.0))
- [ ] Servers: Document context values (see [v1.1.0 release notes](https://github.com/connectrpc/connect-es/releases/tag/v1.1.0))
- [ ] Servers: Document Connect timeouts (see [connect-es#591](https://github.com/connectrpc/connect-es/pull/591)).
- [ ] Servers: Add guide on how to handle errors, document behavior of `yield` in service implementations.
- [x] Servers: Document JSON and binary options (Any and JSON).
- [ ] Servers: Document the shutdownSignal option (also see [connect-es#802](https://github.com/connectrpc/connect-es/issues/802)).
- [ ] Node.js clients: Document best practices for client-streaming and bidi RPCs, explain async iterables, show createWritableIterable().
- [ ] Node.js: Document compressions settings for clients and servers, including read/write limits.
- [ ] Node.js: Document H2 session management (see [connect-es#673](https://github.com/connectrpc/connect-es/pull/673), https://github.com/connectrpc/connect-es/issues/1276).
- [ ] Node.js: Document how to work with errors in the vain of how Connect-Go has its own errors page for returning errors from services.
- [ ] Node.js: Document how to pin certificates and other typical gRPC use cases (see [connect-es#1396](https://github.com/connectrpc/connect-es/issues/1396)).

**Comment by polRk** [comment]
FYI: https://grpc.io/docs/guides/deadlines/#deadline-propagation
